### ISSUE TITLE
Graphic "runs away" when try to pan or zoom

### ISSUE THREAD

**Issue by kupix** [talos/jquery-svgpan#3]
This affects SVGPan.js so I thought I'd try your library too.  Try the following SVG - 

``` xml
<svg height="100%" id="outer" style="position=absolute;display=block;" version="1.1" width="100%" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <svg x="50%" y="50%" overflow="visible" id="inner">
  <g id="viewport" transform="scale(1) translate(-224, -128)">
   <rect height="256" style="fill:grey;stroke:black;" width="448"/>
  </g>
 </svg>
</svg>
```

http://code.google.com/p/svgpan/issues/detail?id=16

**Comment by talos** [comment]
I don't see any way one could support panning on an inner SVG when its location depends upon the outer SVG.  However, it is possible to pan on the outer SVG when the inner SVG's location depends upon the outer SVG.  See this gist:

https://gist.github.com/1993019

Which you can try out here:

http://blog.accursedware.com/jquery-svgpan/jquery-svgpan-nested.html

In effect, switch the nesting of the `<g />` and `<svg />` to be as follows:

``` html
<svg height="100%" id="outer" style="position=absolute;display=block;" version="1.1" width="100%" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <g id="viewport" transform="scale(1) translate(-224, -128)">
  <svg x="50%" y="50%" overflow="visible" id="inner">
   <rect height="256" style="fill:grey;stroke:black;" width="448"/>
  </svg>
 </g>
</svg>
```

And then call `$.svgPan` (or just embed the origin SVG pan library) on the outer SVG:

``` js
$('svg#outer').svgPan('viewport');
```

**Comment by kupix** [comment]
Perfect, that works for me.  Many thanks talos.
