### ISSUE TITLE
Doesn't zoom to mouse location

### ISSUE THREAD

**Issue by blacktm** [talos/jquery-svgpan#4]
I noticed that this version doesn't zoom around the precise mouse location. You can see this difference when comparing the original SVGPan while hovering the cursor over a state and scrolling, zooms to that area...
http://www.cyberz.org/projects/SVGPan/architecture_by_location.svg

...where the jQuery version does not
http://blog.accursedware.com/jquery-svgpan/demo.html

I tried to find where there might be a difference in the code, but looks about identical. Not a deal breaker, but just curious.

P.S. Great plugin BTW. I spent hours trying (failing) to append the original version to dynamic SVGs from D3. Soooo happy you did this. Thanks!

**Comment by talos** [comment]
Yep, this is entirely true.  I'm not sure when I'll get a chance to fix this, but it would be nice to have it work correctly.  My hunch as to why it doesn't work is that the original SVGPan code assumes that the SVG fills the entirety of the window.  I'll update the issue with details/a fix when I get a chance.

**Comment by blacktm** [comment]
Yea, that's exactly what it is. I put the SVG in a fresh body tag and it worked like the original. Not sure how to fix it, I'll do some research.

Basically, I just want to do this: http://polymaps.org/ex/population.html
Damn mbostock and his genius!

**Comment by erichandsmith** [comment]
I played around with this, and I think this can be fixed by changing the getEventPoint function to use offsetX and offsetY.

Also, I fiddled with the demo.html's update function, to map the mouse position to the viewport's current transformation:

   //vertices[0] = d3.svg.mouse(this);
   var p = this.createSVGPoint();
   p.x = d3.mouse(this)[0];
   p.y = d3.mouse(this)[1];
   p = p.matrixTransform(this.getElementById("viewport").getCTM().inverse());
   vertices[0] = [p.x, p.y];

**Comment by talos** [comment]
Interesting -- if you can package the change into a pull request, I can test it out and merge it in.  Otherwise, I may have some time this weekend to integrate the change myself.

Thanks!

**Comment by talos** [comment]
I've tested this and merged it in with 3448819d859d730d08f1192b3d3127d3b041a3cf.  Thanks again for the fix.

**Comment by talos** [comment]
Not totally sure why git's diff is borking on this one -- I suspect line ending issues?  But the changes are here:

https://github.com/talos/jquery-svgpan/blob/3448819d859d730d08f1192b3d3127d3b041a3cf/demo.html#L125

**Comment by talos** [comment]
Actually, realizing that the original intention of this issue ("Doesn't zoom to mouse location") wasn't solved with the d3 fix.  Will fix with another commit momentarily.

**Comment by talos** [comment]
OK, now the original issue is fixed with 0eb9f5c13753da949a5f0f3832c71de2a8f6a1f2.

**Comment by Rush** [comment]
I am not sure if it is related to the previous problem but description of the issue matches what I experience. Basically I embed my  SVG like this:
`<div id="#viewarea"><svg><g id="viewport"><svg id="mysvg"> .........</svg></g></svg></div>`
Everything worked perfectly in Chrome, whilst in Firefox mouse-wheel zooming inside of element does not zoom to the element itself but somehow shifted. I have checked that point from `p = p.matrixTransform(g.getCTM().inverse());` inside `handleMouseWheel` is somehow totally wrong. Inside Chrome the point's value stays more or less the same and in Firefox it increases with zoom as though it was transformed as well. Please let me know how I can help in understanding the issue. ;)

I attach URL which shows my usage: http://rushbase.net/~rush/demo/main.html

**Comment by mugwhump** [comment]
@RushPL 
Yep, I was having the same issue with Firefox. To fix it, I changed getEventPoint to always use pageX and pageY, which the jQuery doc says is browser-independent:

```
offset = $parent.offset();
offsetX = evt.pageX - offset.left;
offsetY = evt.pageY - offset.top;
```

Keep in mind that my svg was inside a div of the same size, which may be important for $parent.offset() to be correct.
